### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by linzexin022**
Curseforge Credit: Godzmoline

### CODE REVIEW

**Review by Juuxel — CHANGES_REQUESTED** [review]
Seems good otherwise, but please don't refer to fixed bugs in places like the stone torch description.

**Comment by linzexin022** [comment]
Revised.

**Comment by linzexin022** [comment]
Updated BYG compat!

**Review by Juuxel — APPROVED** [review]

**Comment by Juuxel** [comment]
Thanks for the translation update 😃

**Comment by EnterFor** [comment]
@linzexin022 嗨，您有时间更新一下这个翻译吗？❤

**Pull request merged**
