### PR TITLE
Rival Cooking For Blockheads' sink

### PR DESCRIPTION
**Pull request by ramidzkh**
This is entirely balanced

Mekanism devs are literally shaking right now

### CODE REVIEW

**Comment by Juuxel** [comment]
I don't think this is a good fit for Adorn. I might add fluid transfer to kitchen sinks in the future (and possibly even an infinite water source in some form!) but not like this, sorry.

**Comment by ramidzkh** [comment]
what if i removed the auto ejecting 🥺👉👈

**Comment by Juuxel** [comment]
Hmm sure, I guess it could work. But only when the sink has water :yeef:

**Comment by ramidzkh** [comment]
wait for the water to render i'd need to make a custom baked model right? :pain:

**Pull request closed without merging**
